ALTER TABLE vehicle
  ADD COLUMN brand VARCHAR(80) NULL AFTER plate,
  ADD COLUMN model VARCHAR(80) NULL AFTER brand,
  ADD COLUMN color VARCHAR(40) NULL AFTER model,
  ADD COLUMN type  VARCHAR(40) NULL AFTER color;
